name: Build CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.7.5'
        architecture: 'x64'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    # - name: Install Node.js modules
    #   run: |
    #     npm install
    #     npm install --global convert-svg-to-png

    - name: Clone master branch
      run: |
        mkdir buildtmp
        git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" --branch master --single-branch ./buildtmp


    - name: Build
      run: |
        python build.py
      working-directory: ./buildtmp/.github/workflows


    - name: Set git config and add changes
      run: |
        git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
        git config --global user.name "${GITHUB_ACTOR}"
        git add --all
      working-directory: ./buildtmp
    - name: Commit, push and send notification
      run: |
        COMMIT_MESSAGE="Update Github Pages"
        git diff-index --quiet --cached HEAD -- && echo "No changes" && exit 0 || echo $COMMIT_MESSAGE
        git commit -m "${COMMIT_MESSAGE}"
        git push https://${{secrets.ACCESS_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git master
        
        curl "https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendMessage?text=$COMMIT_MESSAGE %0ALook at svg.n-panuhin.info %0ARepository%3A github.com/${GITHUB_REPOSITORY}&chat_id=${{secrets.ADMIN_ID}}"
      working-directory: ./buildtmp
